// src/components/Header.jsx
import React from "react";
import styled from "styled-components";

import Github from "src/assets/images/github.svg";
import LinkedIn from "src/assets/images/linkedin.svg";
import Twitter from "src/assets/images/twitter.svg";

const Header = styled.header`
  height: 6em;
  background: #ffffff;
  color: #000000;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
`;

const H1 = styled.h1`
  font-size: 2.45rem;
  margin: 0;
  padding: 0.1em 0;
  font-weight: 400;
  text-align: center;
`;

const SocialContainer = styled.div`
  display: flex;
  width: 100%;
  justify-content: center;
`;

const Social = styled.img`
  width: 1.4em;
  height: 1.6em;
  padding: 0 0.4em;
`;

const SocialLink = ({ src, link }) => (
  <a href={link} target="_blank" rel="noopener noreferrer">
    <Social src={src} />
  </a>
);

export default () => {
  return (
    <Header>
      <H1>~ nowke ~</H1>
      <SocialContainer>
        <SocialLink src={Github} link="https://github.com/nowke" />
        <SocialLink src={LinkedIn} link="https://www.linkedin.com/in/nowke/" />
        <SocialLink src={Twitter} link="https://twitter.com/inowke" />
      </SocialContainer>
    </Header>
  );
};

// components/header.vue
<template>
  <header>
    <v-container>
      <div class="header-content">
        <div color="primary" class="text-h5">
          Navaneesh Kumar
        </div>
        <v-spacer />
        <v-btn icon dark href="https://github.com/nowke/" large>
          <v-icon>mdi-github</v-icon>
        </v-btn>
        <v-btn icon dark href="https://www.linkedin.com/in/nowke/" large>
          <v-icon>mdi-linkedin</v-icon>
        </v-btn>
        <v-btn icon dark href="https://twitter.com/inowke" large>
          <v-icon>mdi-twitter</v-icon>
        </v-btn>
        <v-btn icon dark href="https://dev.to/nowke" large>
          <v-icon>mdi-dev-to</v-icon>
        </v-btn>
      </div>
    </v-container>
  </header>
</template>

<script>
import { Component, Vue } from 'nuxt-property-decorator'

@Component({ name: 'Header' })
class Header extends Vue {}

export default Header
</script>

<style lang="scss" scoped>
header {
  background: #4c4c9d;
  color: #fff;
  height: 65px;
  display: flex;
  align-items: center;
}

.header-content {
  display: flex;
  align-items: center;
}
</style>
